# Generated by Django 5.0.6 on 2024-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_fontschoose'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('api_id', models.CharField(max_length=100)),
                ('voice', models.FileField(upload_to='voice_models/')),
            ],
        ),
    ]
