# Generated by Django 5.0.6 on 2024-10-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_processedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedvideo',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
